version: '3'

services:
  mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - hris_web_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"

  web:
    build: .
    volumes:
      - .:/hris-web
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  hris_web_mysql:
    driver: local
